# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: po-hs
version: '0.0.1'
github: "wisn/po-hs"
license: MIT
author: "Wisnu Adi Nurcahyo"
maintainer: "Wisnu Adi Nurcahyo"
# synopsis: A new Haskeleton package.
# description: po-hs is a new Haskeleton package.
# category: Other

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml

ghc-options: -Wall

library:
  dependencies:
  - base
  source-dirs: library

executables:
  po-hs:
    source-dirs: executable
    main: Main.hs
    dependencies:
    - base
    - po-hs
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

benchmarks:
  po-hs-benchmarks:
    source-dirs: benchmark
    main: Main.hs
    dependencies:
    - base
    - po-hs
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

tests:
  po-hs-test-suite:
    source-dirs: test-suite
    main: Main.hs
    dependencies:
    - base
    - po-hs
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
