# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: language-po
version: '0.0.1'
github: "wisn/language-po"
license: MIT
author: "Wisnu Adi Nurcahyo"
maintainer: "Wisnu Adi Nurcahyo"
synopsis: A Format-Preserving Portable Object in Haskell.
description: A Format-Preserving Portable Object in Haskell.
category: Language

extra-source-files:
- CHANGELOG.md
- LICENSE
- package.yaml
- README.md
- stack.yaml

ghc-options: -Wall

library:
  dependencies:
  - base
  - text
  source-dirs: library

executables:
  poparser:
    source-dirs: executable
    main: Main.hs
    dependencies:
    - base
    - language-po
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

benchmarks:
  poparser-benchmarks:
    source-dirs: benchmark
    main: Main.hs
    dependencies:
    - base
    - language-po
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

tests:
  poparser-test-suite:
    source-dirs: test-suite
    main: Main.hs
    dependencies:
    - base
    - language-po
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
